# Generated by Django 2.1.4 on 2019-01-16 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_attempt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attempt',
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('user', 'test')},
        ),
    ]
